- hosts: all
  name: Get our Hetzner instance ready for running the demo
  tasks:
    # Download and install Rustup
    - name: Download Rustup Installer
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.rs
        mode: '0755'
        force: 'yes'
      tags:
        - rust
    - name: install rust/cargo
      shell: /tmp/rustup.rs -y
      tags:
        - rust
    - name: Remove Rustup Installer
      file:
        path: /tmp/rustup.rs
        state: absent
    - name: Install the nightly version of rust
      shell: rustup toolchain install nightly
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.cargo/bin"

    # Clone and install the Dataprep repo
    - name: Clone the dataprep repo
      git:
        repo: "{{ dataprep_repo }}"
        version: "{{ dataprep_branch }}"
        dest: "dataprep"
        update: yes
    # For now, just wipe target and install the binary
    - name: Wipe target
      shell: cargo clean
      args:
        chdir: "dataprep"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.cargo/bin"
    - name: Install the Dataprep binary
      # TODO: Something is broken with nightly rust -- so just don't install the binary for now
      #      shell: cargo install --path dataprep
      shell: sleep 5
      args:
        chdir: "dataprep"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.cargo/bin"

    # Copy our TMUX jobs to the user and make them executable
    - name: Copy our torrent jobs to the user
      copy:
        src: "utils/torrent_job.sh"
        dest: "{{ root_path }}/torrent_job.sh"
        mode: '0755'
    - name: Copy our dataprep jobs to the use
      copy:
        src: "utils/dataprep_job.sh"
        dest: "{{ root_path }}/dataprep_job.sh"
        mode: '0755'