- hosts: all
  name: Run our benchmarks
  tasks:
    - name: Make sure the packed path exists
      file:
        path: "{{ packed_path }}"
        state: directory
    - name: Check if the packed path is empty
      shell: "ls -A {{ packed_path }}"
      register: packed_path_contents
      ignore_errors: yes
    - name: If the packed path is not empty, fail
      fail:
        msg: "The packed path is not empty. Please delete the contents of the packed path before running this playbook."
      when: packed_path_contents.stdout != ""
    - name: Make sure manifest.json does not exist
      file:
        path: "manifest.json"
        state: absent
    - name: Pack the dataset with dataprep in a new tmux session
      shell: "tmux new -d dataprep pack -i {{ dataset_path }} -o {{ packed_path }} -m manifest.json; tmux wait -S dataprep"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.cargo/bin"
    - name: Wait for dataprep to finish packing the dataset
      shell: "tmux wait -t dataprep"
      ignore_errors: yes