- hosts: all
  name: Run our demo
  tasks:
    - name: Make sure the packed path exists
      file:
        path: "{{ unpacked_path }}"
        state: directory
    - name: Check if the packed path is empty
      shell: "ls -A {{ packed_path }}"
      register: packed_path_contents
      ignore_errors: yes
    - name: If the packed path is not empty, fail
      fail:
        msg: "The packed path is not empty. Please delete the contents of the packed path before running this playbook."
      when: packed_path_contents.stdout != ""
    - name: Make sure manifest.json exists
      file:
        path: "manifest.json"
        state: present
    - name: Pack the dataset with dataprep in a new tmux session
      shell: "./unpack_job.sh {{ unpacked_path }} {{ ifttt_test_webhook_key }}"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.cargo/bin"
    - debug:
        msg: "
          Waiting for unpack job to finish.
          Feel free to exit this playbook. 
          If you've set up IFTTT, you'll get a notification when the packing is done.
          You can check the status of your job by connecting to your user and running `tmux a`.
        "
    - name: Wait for dataprep to finish packing the dataset
      shell: "tmux wait unpack"
      ignore_errors: yes