- hosts: all
  name: Generate input for the benchmark using the fake-file tool
  tasks:
    # Create the input directory if it doesn't exist
    - name: Create the input directory if it doesn't exist
      file:
        path: "{{ input_path }}"
        state: directory
    - name: Log the generation parameters to the controller
      debug:
        msg: "Generating Input with parameters at {{ input_path }}:
              input_path: {{ input_path }}
              file_structures: {{ file_structures }}
              file_structures_size: {{ file_structures_size }}
              file_structures_max_width: {{ file_structures_max_width }}
              file_structures_max_depth: {{ file_structures_max_depth }}"
    # TODO: spawn as TMUX job

#    - name: Copy our input TMUX job to the user
#      copy:
#        src: "../utils/generate.sh"
#        dest: "/home/{{ ansible_user }}/generate.sh"
#        mode: '0777'

    - name: Generating input, this may take a while.
      shell: "/home/{{ ansible_user }}/generate.sh \
              {{ file_structures_size }} \
              {{ file_structures_max_width }} \
              {{ file_structures_max_depth }} \
              {{ file_structures }} \
              {{ input_path }} \
              {{ ifttt_test_webhook_key }}"
#      shell: "./generate.sh \
#              {{ file_structures_size }} \
#              {{ file_structures_max_width }} \
#              {{ file_structures_max_depth }} \
#              {{ file_structures }} \
#              {{ input_path }} \
#              {{ ifttt_test_webhook_key }}"