- hosts: all
  name: Install Dataprep for a user
  tasks:
    - name: Check if rust is installed
      shell: rustc --version
      register: rustc_version
      ignore_errors: yes
    - fail:
        msg: "Rust is not installed. Please run the rust.yml playbook first."
      when: rustc_version.rc != 0

    # Clone and install the Dataprep repo
    - name: Clone the dataprep repo
      git:
        repo: "https://github.com/banyancomputer/dataprep.git"
        # If the branch is not specified, use the default branch
        version: "{{ dataprep_branch | dev }}"
        dest: "dataprep"
        update: yes
    - name: Install the Dataprep binary
      shell: cargo install --path dataprep
      args:
        chdir: "dataprep"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.cargo/bin"

    # Clone and install the Fake-File repo
    - name: Clone the fake-file repo
      git:
        repo: https://github.com/banyancomputer/fake-file.git
        dest: "fake-file"
        update: yes
    - name: Install the fake-file binary
      shell: cargo +nightly install  --path .
      args:
        chdir: "fake-file"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.cargo/bin"

    - name: Copy our input TMUX job to the user
      copy:
        src: "../utils/generate.sh"
        dest: "/home/{{ ansible_user }}/generate.sh"
        mode: '0755'

    - name: Copy our bench TMUX job to the user
      copy:
        src: "../utils/bench.sh"
        dest: "/home/{{ ansible_user }}/bench.sh"
        mode: '0755'

    - name: Copy our torrent TMUX job to the user
      copy:
        src: "../utils/torrent.sh"
        dest: "/home/{{ ansible_user }}/torrent.sh"
        mode: '0755'

    - name: Copy our pack TMUX job to the user
      copy:
        src: "../utils/pack.sh"
        dest: "/home/{{ ansible_user }}/pack.sh"
        mode: '0755'

    - name: Copy our unpack TMUX job to the user
      copy:
        src: "../utils/unpack.sh"
        dest: "/home/{{ ansible_user }}/unpack.sh"
        mode: '0755'