- hosts: all
  name: Get our Hetzner instance ready for running the demo
  tasks:
    # Install the dependencies - Doesn't check if they are already installed
    # Update Yum
    - name: Update Apt
      become: yes
      apt:
        name: "*"
        state: latest
        force_apt_get: true
    # Install Dependencies
    - name: Install Dependencies
      become: yes
      apt:
        name: "{{ item }}"
        state: present
        force_apt_get: true
      with_items:
        - gcc
        - git
        - aria2
        - tmux
        - nfs-kernel-server
        - nfs-common

    # Make sure the /etc/hosts.readers file exists.
    # This will be populated with the IP addresses of the machines that are allowed to read from the NFS share
    - name: Make sure the /etc/hosts.readers file exists
      become: yes
      file:
        path: /etc/hosts.readers
        state: touch
    # Configure hosts.allow and hosts.deny for NFS
    - name: Configure hosts.allow
      become: yes
      lineinfile:
        path: /etc/hosts.allow
        line: "{{ item }}: /etc/hosts.readers"
        state: present
      with_items:
        - portmap
        - lockd
        - mountd
        - statd
    - name: Configure hosts.deny
      become: yes
      lineinfile:
        path: /etc/hosts.deny
        line: "{{ item }}: ALL"
        state: present
      with_items:
        - portmap
        - lockd
        - mountd
        - statd

    - name: Make sure the /etc/exports file exists
      become: yes
      file:
        path: /etc/exports
        state: touch
    - name: Make sure the /home/exports directory exists
      become: yes
      file:
        path: /home/exports
        state: directory
        owner: admin
        group: admin
        mode: '0777'