# Setup a Hetzner instance to setup a specified user
# Allows to configure:
# - username
# - sudo access (with no password)
# - ssh pub key
# The specified user will be created if it does not exist
# Its permissions will be updated if they are different
# If a user is a sudoer, then it will be able to run any command without a password
# The specified ssh pub key will be added to the user's authorized_keys
# If the user already has a different ssh pub key, it will be removed
# Must be run as sudoer

- hosts: all
  name: Setup a Hetzner instance with a specified user
  tasks:
    - name: Determine if the controlling user is root
      set_fact:
        is_root: "{{ ansible_user_id == 'root' }}"

    # Create the user if it does not exist
    - name: Generate a random password
      set_fact:
        # You really shouldn't need this for anything
        user_password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
    - name: Create the user
      become: yes
      user:
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        shell: /bin/bash
        update_password: always
        state: present
    - name: Save the user's password to a file on the instance
      become: yes
      copy:
        content: "{{ user_password }}"
        dest: /home/{{ user_name }}/{{ user_name }}.password
        mode: '0600'
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    # Setup the user's ssh pub key
    # Get the admin users ssh pub key
    - name: Get the admin user's ssh pub key
      become: yes
      shell: "cat /home/{{ ansible_user_id }}/.ssh/authorized_keys"
      register: admin_ssh_pub_key
      when: not is_root
    - name: Get the users ssh pub key from the control machine
      set_fact:
        user_ssh_pub_key: "{{ lookup('file', '{{ user_ssh_pub_key_path }}') }}"
      when: user_ssh_pub_key_path is defined

    - name: Make sure the user has a .ssh directory
      become: yes
      file:
        path: /home/{{ user_name }}/.ssh
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0700'
    - name: Make sure the user has an authorized_keys file
      become: yes
      file:
        path: /home/{{ user_name }}/.ssh/authorized_keys
        state: touch
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0600'
    - name: Add the admin's ssh pub key
      become: yes
      lineinfile:
        path: /home/{{ user_name }}/.ssh/authorized_keys
        line: "{{ admin_ssh_pub_key.stdout }}"
        state: present
        regexp: "^{{ admin_ssh_pub_key.stdout }}"
      when: not is_root
      ignore_errors: yes
    - name: Add the user's ssh pub key
      become: yes
      lineinfile:
        path: /home/{{ user_name }}/.ssh/authorized_keys
        line: "{{ user_ssh_pub_key }}"
        state: present
        regexp: "^{{ user_ssh_pub_key }}"
      when: user_ssh_pub_key is defined

    # Setup the User's exports
    - name: Make sure the user has an exports directory
      become: yes
      file:
        path: /home/exports/{{ user_name }}
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        # User can write, but no one else can
        mode: '0755'
      when: not is_root

    # Make the user an admin if we are root
    - name: Create an admin group if it does not exist
      become: yes
      group:
        name: admin
        state: present
      when: is_root
    - name: Make the user an admin
      become: yes
      user:
        name: "{{ user_name }}"
        groups: admin
        append: yes
        state: present
      when: is_root
#   This is setup by default on our Hetzner instances, so this is assumed. We keep it here for reference.
#    - name: Allow the admin group to run any command without a password
#      become: yes
#      lineinfile:
#        path: /etc/sudoers
#        line: "%admin ALL=(ALL) NOPASSWD: ALL"
#        state: present
#        regexp: "^%admin ALL=(ALL) NOPASSWD: ALL"
#      when: is_root

    # Disable root login - lock the door behind us.
    - name: Disable root login
      become: yes
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "PermitRootLogin no"
        state: present
        regexp: "^PermitRootLogin"
      when: is_root
    - name: Disable password login
      become: yes
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "PasswordAuthentication no"
        state: present
        regexp: "^PasswordAuthentication"
      when: is_root
    - name: Enable ssh key login
      become: yes
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "PubkeyAuthentication yes"
        state: present
        regexp: "^PubkeyAuthentication"
      when: is_root
    - name: Restart sshd
      become: yes
      service:
        name: sshd
        state: restarted
      when: is_root