# Install our Rust binaries on the host
# Requires having Git, Rust, Cargo, and the nightly version of Rust installed on the host
# Arguments:
# -e bench_path=/home # The directory where we clone the Dataprep repo and build the benches

# Run as root
- become: yes
  hosts: all
  tasks:
    # Check if the bench_path exists
    - name: Check if the bench_path exists
      stat:
        path: "{{ bench_path }}"
      register: bench_path_exists
    # Check if the bench_path is a directory owned by the user
    - name: Check if the bench_path is a directory owned by the user
      stat:
        path: "{{ bench_path }}"
        get_attributes: yes
      register: bench_path_stat
      when: bench_path_exists.stat.exists
    # Create and own bench_path if it doesn't exist
    - name: Create and own bench_path if it doesn't exist
      file:
        path: "{{ bench_path }}"
        state: directory
        owner: "{{ ansible_user }}"
      when: not bench_path_exists.stat.exists

    # Clone and build the benches in the Dataprep repo
    - name: Clone the dataprep repo
      git:
        repo: https://github.com/banyancomputer/dataprep.git
        dest: "{{ bench_path }}/dataprep"
        update: yes
    # For now, just wipe target and build the benches
    - name: Wipe target
      shell: cargo +nightly clean
      args:
        chdir: "{{ bench_path }}/dataprep"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.cargo/bin"
    - name: Build production bencher
      shell: cargo +nightly build --bench pipeline --release
      args:
        chdir: "{{ bench_path }}/dataprep"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.cargo/bin"