# Run our tests
# Orchestrate and run tests on the host machine

# Usage
# ansible-playbook -i inventory/localhost run.yml
# -e test_set_path=/home/dataprep/test_set
# -e packed_path=/home/dataprep/packed
# -e unpacked_path=/home/dataprep/unpacked
# -e manifest_path=/home/dataprep/manifest
# -e result_path=/home/dataprep/result
# -e install_path=/home/dataprep

- become: yes
  hosts: all
  name: Run our tests
  tasks:
    # Create a directory to store our manifests
    - name: Create a directory to store our manifests
      file:
        path: "{{ manifest_path }}"
        state: directory
        mode: 0755
        owner: "{{ ansible_user }}"
      when: manifest_path is defined
    - name: Make sure the Results directory exists
      file:
        path: "{{ result_path }}"
        state: directory
        mode: 0755
        owner: "{{ ansible_user }}"
      when: result_path is defined
    # TODO (amiller68): Use cargo binary to run tests directly
    # Run run.sh on the host
    - name: Run our tests
      shell: "run {{ test_set_path }} {{ packed_path }} {{ unpacked_path }} {{ manifest_path }} {{ result_path }}"
      register: run_tests
      # Note (amiller68): This is important for running on AWS
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
    - debug:
        var: run_tests.stdout_lines