- hosts: all
  name: Setup NFS on the host
  tasks:
    # Make sure the /etc/hosts.readers file exists.
    # This will be populated with the IP addresses of the machines that are allowed to read from the NFS share
    - name: Make sure the /etc/hosts.readers file exists
      become: yes
      file:
        path: /etc/hosts.readers
        state: touch
    # Configure hosts.allow and hosts.deny for NFS
    - name: Configure hosts.allow
      become: yes
      lineinfile:
        path: /etc/hosts.allow
        line: "{{ item }}: /etc/hosts.readers"
        state: present
      with_items:
        - portmap
        - lockd
        - mountd
        - statd
    - name: Configure hosts.deny
      become: yes
      lineinfile:
        path: /etc/hosts.deny
        line: "{{ item }}: ALL"
        state: present
      with_items:
        - portmap
        - lockd
        - mountd
        - statd

    - name: Make sure the /etc/exports file exists
      become: yes
      file:
        path: /etc/exports
        state: touch


    - name: Make sure the export path exists
      become: yes
      file:
        path: "{{ export_path }}"
        state: directory
