# Check if our flag files exist in the bench path
# Usage
# -e bench_path=/home/dataprep/bench



- hosts: all
  name: Check if our flag files exist in the bench path
  tasks:
    # Remove the files in the input path
    - name: Remove the files in the input path
      file:
        path: "{{ input_path }}"
        state: absent
    # Make sure the input path is an empty directory
    - name: Make sure the input path is an empty directory
      file:
        path: "{{ input_path }}"
        state: directory
